#!/user/bin/env bash
# ssh client config file
Host *
      PasswordAuthentication no
      IdentifyFile ~/.ssh/school
      SendEnv LANG LC_*
      HashKnownHosts yes
      GSSAPIAuthentication yes
      GSSAPIDelegateCredentials no
